/** Fallback crop data — Kerala home garden plants */
export const FALLBACK_CROPS = [
  { id: "tomato",      name: "Tomato (Thakkali)",          diseases_count: 5, icon: "🍅" },
  { id: "chilli",      name: "Green Chilli (Mulaku)",      diseases_count: 4, icon: "🌶️" },
  { id: "brinjal",     name: "Brinjal (Vazhuthana)",       diseases_count: 4, icon: "🍆" },
  { id: "okra",        name: "Okra (Vendakka)",            diseases_count: 3, icon: "🫛" },
  { id: "cucumber",    name: "Cucumber (Vellarikka)",      diseases_count: 4, icon: "🥒" },
  { id: "bittergourd", name: "Bitter Gourd (Pavakka)",     diseases_count: 3, icon: "🥬" },
  { id: "snakegourd",  name: "Snake Gourd (Padavalanga)",  diseases_count: 3, icon: "🌿" },
  { id: "banana",      name: "Banana (Vazhapazham)",       diseases_count: 4, icon: "🍌" },
  { id: "coconut",     name: "Coconut (Thenga)",           diseases_count: 4, icon: "🥥" },
  { id: "mango",       name: "Mango (Manga)",              diseases_count: 4, icon: "🥭" },
  { id: "papaya",      name: "Papaya (Kappakka)",          diseases_count: 3, icon: "🍈" },
  { id: "curry_leaf",  name: "Curry Leaf (Kariveppila)",   diseases_count: 3, icon: "🌿" },
  { id: "drumstick",   name: "Drumstick (Muringakka)",     diseases_count: 3, icon: "🥢" },
  { id: "tapioca",     name: "Tapioca (Kappa)",            diseases_count: 4, icon: "🫛" },
  { id: "cowpea",      name: "Cowpea (Payar)",             diseases_count: 3, icon: "🫘" },
  { id: "pumpkin",     name: "Pumpkin (Mathanga)",          diseases_count: 4, icon: "🎃" },
  { id: "spinach",     name: "Spinach (Cheera)",           diseases_count: 3, icon: "🥬" },
  { id: "jackfruit",   name: "Jackfruit (Chakka)",         diseases_count: 3, icon: "🍈" },
  { id: "pepper_vine", name: "Black Pepper (Kurumulaku)",  diseases_count: 4, icon: "🫚" },
  { id: "turmeric",    name: "Turmeric (Manjal)",          diseases_count: 3, icon: "🟡" },
];
